import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import { spawnSync } from 'child_process';

const MIGRATION_LOCK = 'migration_lock.toml';

function prismaMigrationTimestampUtc(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`;
}

/**
 * Deletes every migration subfolder under `prisma/migrations`, keeps `migration_lock.toml`,
 * then writes a single `*_init/migration.sql` that builds the current schema from empty
 * (`prisma migrate diff --from-empty --to-schema ...`).
 */
export function squashMigrationsToInit(): { migrationDir: string; sqlPath: string } {
  const cwd = process.cwd();
  const migrationsRoot = join(cwd, 'prisma', 'migrations');

  if (!existsSync(migrationsRoot)) {
    throw new Error(`Migrations directory not found: ${migrationsRoot}`);
  }

  const entries = readdirSync(migrationsRoot, { withFileTypes: true });
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    rmSync(join(migrationsRoot, e.name), { recursive: true, force: true });
  }

  const dirName = `${prismaMigrationTimestampUtc()}_init`;
  const migrationDir = join(migrationsRoot, dirName);
  const sqlPath = join(migrationDir, 'migration.sql');
  mkdirSync(migrationDir, { recursive: true });

  const schemaFile = join(cwd, 'prisma', 'schema.prisma');
  if (!existsSync(schemaFile)) {
    throw new Error(`Schema not found: ${schemaFile}`);
  }

  // Forward slashes work on Windows and Linux for the Prisma CLI.
  const schemaArg = '--to-schema=prisma/schema.prisma';
  const r = spawnSync(
    'npx',
    ['prisma', 'migrate', 'diff', '--from-empty', schemaArg, '--script', '-o', sqlPath],
    {
      cwd,
      env: process.env,
      stdio: ['inherit', 'inherit', 'inherit'],
      shell: process.platform === 'win32',
    },
  );

  if (r.status !== 0) {
    throw new Error(`prisma migrate diff failed with exit code ${r.status ?? 'unknown'}.`);
  }

  if (!existsSync(sqlPath)) {
    throw new Error(`Expected migration file was not created: ${sqlPath}`);
  }

  const sql = readFileSync(sqlPath, 'utf-8');
  if (!sql.trim()) {
    throw new Error(`Generated ${sqlPath} is empty — check prisma/schema.prisma and Prisma config.`);
  }

  const lockPath = join(migrationsRoot, MIGRATION_LOCK);
  if (!existsSync(lockPath)) {
    writeFileSync(
      lockPath,
      `# Please do not edit this file manually\n# It should be added in your version-control system (e.g. Git)\nprovider = "postgresql"\n`,
      'utf-8',
    );
  }

  return { migrationDir, sqlPath };
}
