-- Split legacy flat AccountType into AccountType (department) + StaffRole (job title).

CREATE TYPE "AccountType_new" AS ENUM (
  'BILLING',
  'ACCOUNTING',
  'PHARMACY',
  'NURSE',
  'PHYSICIAN',
  'LABORATORY',
  'RADIOLOGY',
  'STORE',
  'MEDICAL_RECORDS',
  'FRONT_DESK',
  'ICT',
  'CMD',
  'CMAC',
  'SUPER_ADMIN'
);

CREATE TYPE "StaffRole" AS ENUM (
  'BILLING_HEAD',
  'BILLING_STAFF',
  'ACCOUNT_HEAD',
  'ACCOUNTING_STAFF',
  'PHARMACY_STORE',
  'PHARMACY_DISPENSARY',
  'PHARMACY_HEAD',
  'HEAD_NURSE',
  'INPATIENT_NURSE',
  'OUTPATIENT_NURSE',
  'CONSULTANT',
  'RESIDENT',
  'INTERN',
  'JUNIOR_RESIDENT',
  'SENIOR_RESIDENT',
  'CHIEF_RESIDENT',
  'MEDICAL_STUDENT',
  'LAB_HEAD',
  'LAB_SCIENTIST',
  'RADIOLOGY_HEAD',
  'RADIOGRAPHER',
  'RADIOLOGY_RECEPTIONIST',
  'HEAD_OF_STORE',
  'STOREKEEPER',
  'MEDICAL_RECORDS',
  'FRONT_DESK',
  'ICT_STAFF',
  'CMD',
  'CMAC',
  'SUPER_ADMIN'
);

ALTER TYPE "AccountType" RENAME TO "AccountType_old";

ALTER TABLE "Staff" ADD COLUMN "accountType_new" "AccountType_new";
ALTER TABLE "Staff" ADD COLUMN "staffRole" "StaffRole";

UPDATE "Staff"
SET
  "accountType_new" = (
    CASE COALESCE("accountType"::text, 'OTHER')
      WHEN 'PHARMACY_STORE' THEN 'PHARMACY'
      WHEN 'PHARMACY_DISPENSARY' THEN 'PHARMACY'
      WHEN 'PHARMACY_HEAD' THEN 'PHARMACY'
      WHEN 'INPATIENT_NURSE' THEN 'NURSE'
      WHEN 'OUTPATIENT_NURSE' THEN 'NURSE'
      WHEN 'INPATIENT_DOCTOR' THEN 'PHYSICIAN'
      WHEN 'MEDICAL_RECORDS' THEN 'MEDICAL_RECORDS'
      WHEN 'OTHER' THEN 'SUPER_ADMIN'
      WHEN 'FRONTDESK' THEN 'FRONT_DESK'
      WHEN 'CONSULTANT' THEN 'PHYSICIAN'
      WHEN 'NURSE' THEN 'NURSE'
      WHEN 'LAB' THEN 'LABORATORY'
      WHEN 'RADIOLOGY' THEN 'RADIOLOGY'
      WHEN 'RADIOLOGIST' THEN 'RADIOLOGY'
      WHEN 'RADIOGRAPHER' THEN 'RADIOLOGY'
      WHEN 'RADIOLOGY_RECEPTIONIST' THEN 'RADIOLOGY'
      WHEN 'ACCOUNTS' THEN 'ACCOUNTING'
      WHEN 'BILLS' THEN 'BILLING'
      WHEN 'PHARMACY' THEN 'PHARMACY'
      WHEN 'THEATERE' THEN 'PHYSICIAN'
      WHEN 'ONG' THEN 'PHYSICIAN'
      WHEN 'DIALYSIS' THEN 'PHYSICIAN'
      WHEN 'STORE' THEN 'STORE'
      ELSE 'SUPER_ADMIN'
    END
  )::"AccountType_new",
  "staffRole" = (
    CASE COALESCE("accountType"::text, 'OTHER')
      WHEN 'PHARMACY_STORE' THEN 'PHARMACY_STORE'
      WHEN 'PHARMACY_DISPENSARY' THEN 'PHARMACY_DISPENSARY'
      WHEN 'PHARMACY_HEAD' THEN 'PHARMACY_HEAD'
      WHEN 'INPATIENT_NURSE' THEN 'INPATIENT_NURSE'
      WHEN 'OUTPATIENT_NURSE' THEN 'OUTPATIENT_NURSE'
      WHEN 'INPATIENT_DOCTOR' THEN 'RESIDENT'
      WHEN 'MEDICAL_RECORDS' THEN 'MEDICAL_RECORDS'
      WHEN 'OTHER' THEN 'SUPER_ADMIN'
      WHEN 'FRONTDESK' THEN 'FRONT_DESK'
      WHEN 'CONSULTANT' THEN 'CONSULTANT'
      WHEN 'NURSE' THEN 'OUTPATIENT_NURSE'
      WHEN 'LAB' THEN 'LAB_SCIENTIST'
      WHEN 'RADIOLOGY' THEN 'RADIOLOGY_HEAD'
      WHEN 'RADIOLOGIST' THEN 'RADIOLOGY_HEAD'
      WHEN 'RADIOGRAPHER' THEN 'RADIOGRAPHER'
      WHEN 'RADIOLOGY_RECEPTIONIST' THEN 'RADIOLOGY_RECEPTIONIST'
      WHEN 'ACCOUNTS' THEN 'ACCOUNTING_STAFF'
      WHEN 'BILLS' THEN 'BILLING_STAFF'
      WHEN 'PHARMACY' THEN 'PHARMACY_DISPENSARY'
      WHEN 'THEATERE' THEN 'CONSULTANT'
      WHEN 'ONG' THEN 'CONSULTANT'
      WHEN 'DIALYSIS' THEN 'RESIDENT'
      WHEN 'STORE' THEN 'STOREKEEPER'
      ELSE 'SUPER_ADMIN'
    END
  )::"StaffRole";

ALTER TABLE "Staff" DROP COLUMN "accountType";
ALTER TABLE "Staff" DROP COLUMN "role";

ALTER TABLE "Staff" RENAME COLUMN "accountType_new" TO "accountType";

ALTER TABLE "Staff" ALTER COLUMN "accountType" SET NOT NULL;
ALTER TABLE "Staff" ALTER COLUMN "staffRole" SET NOT NULL;

DROP TYPE "AccountType_old";

ALTER TYPE "AccountType_new" RENAME TO "AccountType";
